/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateSummaryRouteImport } from './routes/_private/summary'
import { Route as PublicCadastroRouteImport } from './routes/_public/cadastro'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateAccountsIndexRouteImport } from './routes/_private/accounts/index'
import { Route as PrivateCategoriesIndexRouteImport } from './routes/_private/categories/index'
import { Route as PrivateTransactionsIndexRouteImport } from './routes/_private/transactions/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSummaryRoute = PrivateSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicCadastroRoute = PublicCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateAccountsIndexRoute = PrivateAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCategoriesIndexRoute = PrivateCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTransactionsIndexRoute =
  PrivateTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof PrivateProfileRoute
  '/summary': typeof PrivateSummaryRoute
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/accounts/': typeof PrivateAccountsIndexRoute
  '/categories/': typeof PrivateCategoriesIndexRoute
  '/transactions/': typeof PrivateTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof PrivateProfileRoute
  '/summary': typeof PrivateSummaryRoute
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/accounts': typeof PrivateAccountsIndexRoute
  '/categories': typeof PrivateCategoriesIndexRoute
  '/transactions': typeof PrivateTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/summary': typeof PrivateSummaryRoute
  '/_public/cadastro': typeof PublicCadastroRoute
  '/_public/login': typeof PublicLoginRoute
  '/_private/accounts/': typeof PrivateAccountsIndexRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
  '/_private/transactions/': typeof PrivateTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/summary'
    | '/cadastro'
    | '/login'
    | '/accounts/'
    | '/categories/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/summary'
    | '/cadastro'
    | '/login'
    | '/accounts'
    | '/categories'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/profile'
    | '/_private/summary'
    | '/_public/cadastro'
    | '/_public/login'
    | '/_private/accounts/'
    | '/_private/categories/'
    | '/_private/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/summary': {
      id: '/_private/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof PrivateSummaryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/cadastro': {
      id: '/_public/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof PublicCadastroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/accounts/': {
      id: '/_private/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof PrivateAccountsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PrivateCategoriesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/transactions/': {
      id: '/_private/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof PrivateTransactionsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSummaryRoute: typeof PrivateSummaryRoute
  PrivateAccountsIndexRoute: typeof PrivateAccountsIndexRoute
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
  PrivateTransactionsIndexRoute: typeof PrivateTransactionsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSummaryRoute: PrivateSummaryRoute,
  PrivateAccountsIndexRoute: PrivateAccountsIndexRoute,
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
  PrivateTransactionsIndexRoute: PrivateTransactionsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCadastroRoute: typeof PublicCadastroRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCadastroRoute: PublicCadastroRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
