/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateSummaryRouteImport } from './routes/_private/summary'
import { Route as PrivateTransactionsRouteImport } from './routes/_private/transactions'
import { Route as PublicCadastroRouteImport } from './routes/_public/cadastro'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateTransactionsTransactionIdRouteImport } from './routes/_private/transactions.$transactionId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSummaryRoute = PrivateSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTransactionsRoute = PrivateTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicCadastroRoute = PublicCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateTransactionsTransactionIdRoute =
  PrivateTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => PrivateTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile': typeof PrivateProfileRoute
  '/summary': typeof PrivateSummaryRoute
  '/transactions': typeof PrivateTransactionsRouteWithChildren
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/transactions/$transactionId': typeof PrivateTransactionsTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/profile': typeof PrivateProfileRoute
  '/summary': typeof PrivateSummaryRoute
  '/transactions': typeof PrivateTransactionsRouteWithChildren
  '/cadastro': typeof PublicCadastroRoute
  '/login': typeof PublicLoginRoute
  '/transactions/$transactionId': typeof PrivateTransactionsTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/summary': typeof PrivateSummaryRoute
  '/_private/transactions': typeof PrivateTransactionsRouteWithChildren
  '/_public/cadastro': typeof PublicCadastroRoute
  '/_public/login': typeof PublicLoginRoute
  '/_private/transactions/$transactionId': typeof PrivateTransactionsTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/profile'
    | '/summary'
    | '/transactions'
    | '/cadastro'
    | '/login'
    | '/transactions/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/profile'
    | '/summary'
    | '/transactions'
    | '/cadastro'
    | '/login'
    | '/transactions/$transactionId'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/$'
    | '/_private/dashboard'
    | '/_private/profile'
    | '/_private/summary'
    | '/_private/transactions'
    | '/_public/cadastro'
    | '/_public/login'
    | '/_private/transactions/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/summary': {
      id: '/_private/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof PrivateSummaryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/transactions': {
      id: '/_private/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof PrivateTransactionsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/cadastro': {
      id: '/_public/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof PublicCadastroRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/transactions/$transactionId': {
      id: '/_private/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof PrivateTransactionsTransactionIdRouteImport
      parentRoute: typeof PrivateTransactionsRoute
    }
  }
}

interface PrivateTransactionsRouteChildren {
  PrivateTransactionsTransactionIdRoute: typeof PrivateTransactionsTransactionIdRoute
}

const PrivateTransactionsRouteChildren: PrivateTransactionsRouteChildren = {
  PrivateTransactionsTransactionIdRoute: PrivateTransactionsTransactionIdRoute,
}

const PrivateTransactionsRouteWithChildren =
  PrivateTransactionsRoute._addFileChildren(PrivateTransactionsRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSummaryRoute: typeof PrivateSummaryRoute
  PrivateTransactionsRoute: typeof PrivateTransactionsRouteWithChildren
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSummaryRoute: PrivateSummaryRoute,
  PrivateTransactionsRoute: PrivateTransactionsRouteWithChildren,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCadastroRoute: typeof PublicCadastroRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCadastroRoute: PublicCadastroRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
